# Build ruff_wasm for npm.
#
# Assumed to run as a subworkflow of .github/workflows/release.yml; specifically, as a local
# artifacts job within `cargo-dist`.
name: "Build wasm"

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string
  pull_request:
    paths:
      - .github/workflows/build-wasm.yml

concurrency:
  group: build-wasm-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-build') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [web, bundler, nodejs]
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "Install Rust toolchain"
        run: rustup target add wasm32-unknown-unknown
      - uses: jetli/wasm-bindgen-action@20b33e20595891ab1a0ed73145d8a21fc96e7c29 # v0.2.0
      - name: "Install wasm-opt"
        run: sudo apt-get update -qq && sudo apt-get install -y -qq binaryen
      - name: "Build ruff_wasm with minimal-size profile"
        run: cargo build --profile minimal-size --target wasm32-unknown-unknown --lib -p ruff_wasm
      - name: "Generate wasm-bindgen bindings"
        run: wasm-bindgen --target ${{ matrix.target }} --out-dir crates/ruff_wasm/pkg target/wasm32-unknown-unknown/minimal-size/ruff_wasm.wasm
      - name: "Optimize wasm binary size"
        run: wasm-opt -Oz crates/ruff_wasm/pkg/ruff_wasm_bg.wasm -o crates/ruff_wasm/pkg/ruff_wasm_bg.wasm
      - name: "Generate package.json"
        run: |
          VERSION=$(cargo metadata --format-version=1 --no-deps -p ruff_wasm | jq -r '.packages[0].version')
          jq -n \
            --arg name "@astral-sh/ruff-wasm-${{ matrix.target }}" \
            --arg version "$VERSION" \
            '{name: $name, version: $version, files: ["ruff_wasm_bg.wasm", "ruff_wasm.js", "ruff_wasm.d.ts", "ruff_wasm_bg.wasm.d.ts"]}' \
            > crates/ruff_wasm/pkg/package.json
      - run: cp LICENSE crates/ruff_wasm/pkg
      - name: "Upload wasm artifact"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          # Avoid prefixing the name with `artifacts-` here to exclude it from the GitHub release.
          name: wasm-npm-${{ matrix.target }}
          path: crates/ruff_wasm/pkg
